const privacyPolicy = [
  'S',
  'elamat datang di Aplikasi Bel Pintar.  Kebijakan privasi ini menjelaskan cara kami mengelola informasi pengguna dalam rangka memberikan layanan pada Aplikasi Bel Pintar. ',
  'h1:Kebijakan Privasi Aplikasi Bel Pintar',
  'i:Terakhir diperbarui 13 Januari 2024',
  'h2:Informasi yang Kami Kumpulkan',
  'Aplikasi Bel Pintar tidak mengumpulkan informasi pribadi dari pengguna. Kami tidak meminta data identifikasi pribadi atau informasi lainnya. ',
  'h2:Penggunaan Layanan',
  'Aplikasi Bel Pintar dirancang untuk memberikan layanan tanpa memerlukan pembayaran. Tidak ada informasi keuangan atau pembayaran yang dikumpulkan atau disimpan.',
  'h2:Iklan',
  'Kami dapat menampilkan iklan dalam Aplikasi Bel Pintar. Iklan ini disajikan oleh penyedia iklan pihak ketiga yang dapat menggunakan teknologi pelacakan untuk menyajikan iklan yang relevan dengan pengguna. Informasi pribadi tidak dikumpulkan oleh iklan tersebut. ',
  'h2:Tautan Eksternal',
  'Aplikasi Bel Pintar dapat menyertakan tautan eksternal ke situs web pihak ketiga. Kami tidak bertanggung jawab atas praktik privasi atau konten situs web tersebut. ',
  'h2:Keamanan',
  'Kami mengambil langkah - langkah keamanan untuk melindungi informasi pengguna dari akses yang tidak sah atau penggunaan yang tidak sah. Namun, karena sifat internet yang terus berkembang, kami tidak dapat menjamin keamanan informasi secara penuh. ',
  'h2:Perubahan pada Kebijakan Privasi',
  'Jika kami melakukan perubahan pada Kebijakan Privasi ini, kami akan memberitahukan pengguna melalui pembaruan aplikasi atau pemberitahuan lainnya. ',
  'h2:Hubungi Kami',
  'Jika Anda memiliki pertanyaan atau kekhawatiran tentang kebijakan privasi kami, silakan hubungi kami di:',
  'i:imronrosadiee@gmail.com',
  'Terima kasih telah menggunakan Aplikasi Bel Pintar. ',
  'h2:BINARY DEV',
];

export default privacyPolicy;
